import React, { useState, useEffect } from 'react';
import apiService from '../services/api';
import './HealthInsights.css';

const HealthInsights = ({ userId }) => {
  const [insights, setInsights] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchInsights();
  }, [userId]);

  const fetchInsights = async () => {
    try {
      setLoading(true);
      setError(null);
      console.log('Fetching insights for user:', userId);
      const response = await apiService.getHealthInsights(userId);
      console.log('Insights response:', response);
      
      if (response.success && response.insights) {
        setInsights(response.insights);
      } else if (response.insights) {
        // Handle case where response doesn't have success field
        setInsights(response.insights);
      } else {
        setError('No insights data received');
      }
    } catch (err) {
      setError(err.message || 'Failed to fetch health insights');
      console.error('Error fetching insights:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleRefresh = () => {
    fetchInsights();
  };

  if (loading) {
    return (
      <div className="insights-container">
        <div className="insights-header">
          <h2>🤖 AI Health Insights</h2>
        </div>
        <div className="insights-loading">
          <div className="loading-spinner"></div>
          <p>Analyzing your health data...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="insights-container">
        <div className="insights-header">
          <h2>🤖 AI Health Insights</h2>
          <button className="refresh-btn" onClick={handleRefresh}>
            ↻ Retry
          </button>
        </div>
        <div className="insights-error">
          <p>⚠️ {error}</p>
        </div>
      </div>
    );
  }

  if (!insights) return null;

  return (
    <div className="insights-container">
      <div className="insights-header">
        <h2>🤖 AI Health Insights</h2>
        <button className="refresh-btn" onClick={handleRefresh}>
          ↻ Refresh
        </button>
      </div>

      {/* Summary Section */}
      <div className="insights-section summary-section">
        <h3>📊 Overview</h3>
        <p className="summary-text">{insights.summary}</p>
      </div>

      {/* Statistics Cards */}
      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-icon">📋</div>
          <div className="stat-value">{insights.statistics?.total_records || 0}</div>
          <div className="stat-label">Health Records</div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">👨‍⚕️</div>
          <div className="stat-value">{insights.statistics?.total_doctors || 0}</div>
          <div className="stat-label">Doctors Visited</div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">💊</div>
          <div className="stat-value">{insights.statistics?.total_treatments || 0}</div>
          <div className="stat-label">Treatments</div>
        </div>
        <div className="stat-card">
          <div className="stat-icon">🔔</div>
          <div className="stat-value">{insights.statistics?.recent_visits || 0}</div>
          <div className="stat-label">Recent Visits</div>
        </div>
      </div>

      {/* Trends Section */}
      {insights.trends && insights.trends.length > 0 && (
        <div className="insights-section trends-section">
          <h3>📈 Health Trends & Patterns</h3>
          <ul className="insights-list">
            {insights.trends.map((trend, index) => (
              <li key={index} className="insight-item trend-item">
                <span className="item-icon">▸</span>
                <span className="item-text">{trend}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Recommendations Section */}
      {insights.recommendations && insights.recommendations.length > 0 && (
        <div className="insights-section recommendations-section">
          <h3>💡 Personalized Recommendations</h3>
          <ul className="insights-list">
            {insights.recommendations.map((recommendation, index) => (
              <li key={index} className="insight-item recommendation-item">
                <span className="item-icon">✓</span>
                <span className="item-text">{recommendation}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="insights-footer">
        <p className="disclaimer">
          💡 These insights are generated by AI and should not replace professional medical advice.
          Always consult with your healthcare provider for medical decisions.
        </p>
      </div>
    </div>
  );
};

export default HealthInsights;
